# Generated by Django 6.0.3 on 2026-03-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studysession",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="studysession",
            name="duration",
        ),
        migrations.AddField(
            model_name="studysession",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studysession",
            name="week_number",
            field=models.IntegerField(default=0),
        ),
    ]
